project:
  type: website
  output-dir: docs

website:
  title: "@gracesstew"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/gracesstew
        target: blank
      - icon: linkedin
        href: https://www.linkedin.com/in/gracesstewart
        target: blank

format:
  html:
    theme:
      light: minty
      #dark: slate
    css: styles.css
    toc: true

editor: visual

