project:
  type: website
  output-dir: docs

website:
  title: "@gracesstew"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Experience
      - icon: github
        href: https://github.com/gracesstew
        target: blank
      - icon: linkedin
        href: https://www.linkedin.com/in/gracesstewart
        target: blank
      - icon: bar-chart-fill
        href: https://gracesstew.github.io/dashboards
        target: blank

format:
  html:
    theme:
      light: minty
      #dark: slate
    css: styles.css
    toc: false

editor: visual

